# -*- coding: utf-8 -*-
"""chatbot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPYyRYmicYb3GAg-viFLKwzMBzGAP8on
"""

from nltk.chat.util import Chat, reflections

building = [['my name is (.*)', ['hi %1']],
         ['(hi|hello|hey|holla|hola)', ['hey there\n', 'hi there\n', 'hey\n' ]],
         ['(.*)program management(.*)msb', ['The Program Management office of MSB is located on the first floor of MSB building ^^\n']],
         ['(.*)finance(.*)', ['The Finance Department of SMU is located in the first floor of MSB building\n']],
         ['(.*)student life(.*) ', ['The Student life Department is located right next to Hyppodrome Cafe inside the University\n']],
         ['(.*)Noura Baccar(.*)', ['The office of Ms Noura Baccar is B-210 and located on the second floor of Medtechs building\n']]
]
academics = [['(.*)(preengineering|pre-engineering|pre engineering)(.*)', [' The pre-engineering program provides a basic foundation in the fundamental sciences, engineering basics, and computer and communication skills. It is designed to prepare the students for the challenging demands of the engineering specializations that will follow..\n']],
         ['(.*)(Software Engineering|se masters for software engineering)(.*)', ['MedTech’s Software Engineering SWE program provides a combination of advanced technical and theoretical knowledge, best engineering practices, and emerging technologies to develop software that meet high quality standards.\n']],
         ['(.*)(cs engineering|computer systems|computer engineering|computer systems engineering)(.*)', ['The Computer Systems Engineering CSE program at MedTech prepares students for a productive career in the computing industry. It focuses on the key principles and techniques underlying the design, evaluation, and application of computer systems within a project-based approach. The curriculum covers the important areas of electronic circuits and systems, digital system design, computer architecture, networks, algorithms, and software systems.\n']],
         ['(.*)(renewable|renewable energy|renewable energy engineering|renewable engineering|energy engineering)(.*)', ['MedTech’s Renewable Energy Engineering REE program provides a combination of advanced technical and theoretical knowledge in the rapidly expanding area of renewable energy engineering with a clear Electrical Engineering focus\n']],
         ['(.*)(cs license|cs bachelor|computer science|cs)(.*)', ['MedTech’s Licence in Computer Science seeks to meet the dual objective of ensuring a solid basic training in fundamental areas, such as mathematics and programming, as well as specifics of Computer Engineering. The program helps students to develop a broad spectrum of skills required for pursuing advanced studies or initiating their professional careers.\n']],
         ['(.*)(blockchain|artificial intelligence|ai)(.*)', ['The Master aims at specialized training mainly in the following topics: Blockchain, Artificial Intelligence, Financial and Analytics Technology, Digital Business, and IT & General Management\n']],
         ['(.*)(cyber|security)(.*)', ['The Master program in Cyber Security aims at specialized training in Informatics Security Cybersecurity. Giving response to a set of initiatives that have been developed at the National and International level, targeting the development of knowledge competencies in the field of Cybersecurity (e.g. IFC-UTICA Directive, US Cybersecurity Information Sharing Act, EU Directive for security across the Union) as a way to support the growth of the digital economy, preserving the privacy of citizens, and combat and prevent cybercrime and cyberterrorism\n']],
         ['(.*)(energy|sustainability|management)(.*)', ['The Master in Energy Management and Sustainability at the Mediterranean Institute of Technology MedTech aims at developing its students abilities to contribute to interdisciplinary interventions in areas such as the efficient use of energy, centralized or decentralized energy production, or the distribution of energy, always under a sustainable development perspective.\n']]
]

# val = input("Hi there!\nThis is SMU CHATBOT.\nI am here to answer all your questions.\nHow may I help you today?\n\n1.Finance\n2.Academics\n3.Building\n\n")
def academiaChat(val):
    chat = Chat(academics, reflections)
    response = chat.respond(val)
    return response

def buildingChat(val):
    chat = Chat(building, reflections)
    response = chat.respond(val)
    return response


    # if (int(val)==2):
    #       chat = "You can ask me anything about offices and the place of departments!" + Chat(building, reflections).converse()
    #
    #       return chat
    # elif (int(val)==1):
    #       chat = "You can ask me anything about Medtech Engineering degrees, Bachelors Licence and Masters!" + Chat(academics, reflections).converse()
    #       return chat
    # else:
    #       return "Please choose the numbered option from the menu"